### ISSUE TITLE
Implement an IAsyncInitializer to handle the migrations

### ISSUE THREAD

**Issue by joaofbantunes** [AspNetCoreFromZeroToOverkill/GroupManagement#19]
Implement an `IAsyncInitializer` to handle the migrations, using [AspNetCore.AsyncInitialization](https://github.com/thomaslevesque/AspNetCore.AsyncInitialization), in     `CodingMilitia.PlayBall.Shared.StartupTasks`.

**Comment by romanolester** [comment]
Please assign this to me

**Comment by joaofbantunes** [comment]
I was looking, too assign I think I need to add collaborators. I'll do it when I have a chance.

Meanwhile, you can do as usual: fork the repo, create a branch to work on and then open a pull request 👍

**Comment by romanolester** [comment]
should we close this issue now?

**Comment by joaofbantunes** [comment]
Done in #25
