### ISSUE TITLE
Create some ServiceCollection extensions to make it easier to register the initializer in DI

### ISSUE THREAD

**Issue by joaofbantunes** [AspNetCoreFromZeroToOverkill/GroupManagement#20]

**Comment by romanolester** [comment]
Can you please elaborate? 😁

**Comment by joaofbantunes** [comment]
Maybe this isn't really needed, but we can do it just for the fun of it 😛.
The idea is to create an extension method on the new StartupTasks project, to register the `DbInitializer` task in the DI container.
So instead of what we have now in the `Startup` class:
```csharp
services.AddAsyncInitializer<DbInitializer<GroupManagementDbContext>>();
```
We would have something like:
```csharp
services.AddDbInitializer<GroupManagementDbContext>();
```

Like I said, not particularly important, but it's a bit more obvious, hiding a bit the `AsyncInitialization`, which isn't really important to be explicit.

**Comment by romanolester** [comment]
but hey. The title of the project is ASP.NET Core: From 0 to overkill. So this must be done 😁. please assign me to this issue.

**Comment by joaofbantunes** [comment]
Indeed 😛
