### ISSUE TITLE
DbInitializer should get environments as an argument

### ISSUE THREAD

**Issue by joaofbantunes** [AspNetCoreFromZeroToOverkill/GroupManagement#26]
Instead of having the environments in which the migrations run on startup hardcoded, `DbInitializer` should receive them as arguments in the constructor, probably in a settings object.

**Comment by romanolester** [comment]
How should we do this? Do we declare the variable in our config? How do we create the settings object?

**Comment by joaofbantunes** [comment]
One of the project's episodes was dedicated to that topic 😆
You can check it out [here](https://blog.codingmilitia.com/2018/11/16/aspnet-006-from-zero-to-overkill-configuration).

But in summary, yes, we should create a new class to represent the `DbInitializer` settings, which will probably contain a `string[]` with the environments. We add it to the `appsettings.json` file, and in the `Startup` class we configure it to be used.

**Comment by romanolester** [comment]
Will submit a pull request on what is on my mind on this. .😁

**Comment by joaofbantunes** [comment]
Solved during migration to .NET Core 3.0.
