### ISSUE TITLE
Add Async suffix

### ISSUE THREAD

**Issue by joaofbantunes** [AspNetCoreFromZeroToOverkill/GroupManagement#9]
The `DatabaseExtensions.EnsureDbUpToDate` method is missing the traditional `Async` suffix.

https://github.com/AspNetCoreFromZeroToOverkill/GroupManagement/blob/4bc263d935a603bb389956f566f431cf7ab8d6eb/src/CodingMilitia.PlayBall.GroupManagement.Web/StartupHelpers/DatabaseExtensions.cs#L10

**Comment by romanolester** [comment]
You mean this is just to rename a method right?

**Comment by joaofbantunes** [comment]
Yes, but don't bother with this one, I was just lazy to make the rename and created the issue, which probably took longer 😛.
